### ISSUE TITLE
[nextcloud on android] How does it go? Any specific specs on the phone?

### ISSUE THREAD

**Issue by moshpirit** [jancborchardt/owncloud-scripts#8]
I'm thinking in re-using a Samsung Galaxy S7 edge and I thought Nextcloud could do the work but I'm not sure if will be the best device. Although is a very nice phone ([specs here](https://www.gsmarena.com/samsung_galaxy_s7_edge-7945.php)) 

But before I try anything (I'm just a regular user) I wanted to have some opinions.

**Comment by jancborchardt** [comment]
If i remember correctly, for me it worked on a Nexus 4 phone, and possibly even on a Moto G 1st Gen. So it should be fine on an S7.

In any case you can just try it out as nothing in the process is destructive, at least as described in the tutorial at https://github.com/jancborchardt/nextcloud-scripts/blob/master/nextcloud-on-android.md

**Comment by moshpirit** [comment]
Thanks a lot! Unluckily, after following all your instructions, I couldn't get myself into `http://0.0.0.0:8080`. 
![screenshot](https://i.imgur.com/4JzJDsi.png)

**Comment by moshpirit** [comment]
Thanks a lot! Unluckily, after following all your instructions, I couldn't get myself into `http://0.0.0.0:8080`. 
![screenshot](https://i.imgur.com/4JzJDsi.png)

**Comment by moshpirit** [comment]
OK, I got the error: cloning the `3rdparty` was only mentioned in the *MGit* way so I didn't clone it. I guess this is all the instructions with this then:

## Install (and optionally clone as well) with [Termux](https://termux.com/)
- First install some dependencies `pkg install php php-fpm sqlite coreutils openssl-tool git` (I added `git`)
- Allow Termux to access storage outside of own folder `termux-setup-storage`
- (If you want to clone with Termux: `cd /storage/emulated/0/ && git clone https://github.com/nextcloud/server.git nextcloud &&  git clone https://github.com/nextcloud/3rthparty.git nextcloud/3rdparty`)
- Get the Nextcloud submodules `cd /storage/emulated/0/nextcloud/ && git submodule update --init`
- Start the server `php -S 0.0.0.0:8080 -t /storage/emulated/0/nextcloud/`

## Finish setup in [Firefox](https://www.mozilla.org/firefox/android/)
- Go to `http://0.0.0.0:8080`
- Set an admin username and password 
- (SQLite will be used as database)

**Comment by jancborchardt** [comment]
So I’d say if you want to clone with Termux, this one sentence needs to be adjusted:
> (If you want to clone with Termux: `pkg install git && cd /storage/emulated/0/ && git clone https://github.com/nextcloud/server.git nextcloud && git clone https://github.com/nextcloud/3rdparty.git nextcloud/3rdparty`)

Do you want to submit a pull request for the file about that @moshpirit? :)

**Comment by moshpirit** [comment]
For the `nextcloud-on-android.md` file? if so, sure! :)

BTW, is there any way we could use a localhost instead of 0.0.0.0 so I can connect my laptop or other phones to this Android phone/server? Sorry for the question but I'm not a developer or anything and all of this server stuff is totally new for me haha 😅

**Comment by jancborchardt** [comment]
> BTW, is there any way we could use a localhost instead of 0.0.0.0 so I can connect my laptop or other phones to this Android phone/server? Sorry for the question but I'm not a developer or anything and all of this server stuff is totally new for me haha :sweat_smile: 

Hehe, my background is in design so similar issue here. ;) What you are looking for is a reverse proxy for Android. You could try Pagekite: https://pagekite.net/wiki/Howto/GNULinux/AndroidPageKite/

If that works for you, it would be great if you can submit another pull request to include that in the `nextcloud-on-android.md` file. :)

**Comment by moshpirit** [comment]
Sure! I need to finish some late work I have and then I'll make some research :)
